name: Build and Test Docker Images

on:
  push:
    branches: [main]
    paths:
      - "custom-sandboxes/**"
      - ".github/workflows/docker-build-test.yml"
  pull_request:
    branches: [main]
    paths:
      - "custom-sandboxes/**"
      - ".github/workflows/docker-build-test.yml"

jobs:
  build-amplify-nuxt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Amplify Nuxt image
        uses: docker/build-push-action@v5
        with:
          context: custom-sandboxes/amplify-nuxt
          push: false
          load: true
          tags: amplify-nuxt:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test container
        run: |
          # Test Node.js and npm
          docker run --rm amplify-nuxt:test node --version
          docker run --rm amplify-nuxt:test npm --version
          
          # Test Amplify CLI installation
          docker run --rm amplify-nuxt:test amplify --version
          
          # Test required system dependencies
          docker run --rm amplify-nuxt:test python3 --version
          docker run --rm amplify-nuxt:test git --version
          
          # Test TypeScript installation
          docker run --rm amplify-nuxt:test tsc --version
          
          # Test working directory
          docker run --rm amplify-nuxt:test pwd